# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("GetPrices works", {
  urlgdoctest <-
    "https://docs.google.com/spreadsheets/d/1aTGGqcUAjWg8Lz5sqQ5CzCEN7LbZdKGV_PdQC4YZ6Qw/edit?usp=sharing"
  urlgsheettest <- "26-janv"
  dataset <-ImportAndCleanData(urlgdoc = urlgdoctest, urlgsheet = urlgsheettest)
  expect_equal(
    GetPrices(
      dataset = dataset,
      fonction = "median",
      dobydepartement = FALSE
    ),
    structure(
      list(
        departement = "group",
        PrixGazole = 1.947,
        PrixE10 = 1.899,
        PrixSP98 = 1.979,
        operation = "median"
      ),
      row.names = c(NA,-1L),
      class = c("tbl_df", "tbl", "data.frame")
    )
  )
})
