# WARNING - Generated by {fusen} from /dev/flat_getprices.Rmd: do not edit by hand

test_that("GetPrices works", {
  dataset <-FuelFrontalUtility::DonneesTest
  expect_equal(
    GetPrices(
      dataset = dataset,
      fonction = "median",
      dobydepartement = FALSE
    ),
    structure(
      list(
        departement = "group",
        PrixGazole = 1.947,
        PrixE10 = 1.899,
        PrixSP98 = 1.979,
        operation = "median"
      ),
      row.names = c(NA,-1L),
      class = c("tbl_df", "tbl", "data.frame")
    )
  )
})
