# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' ImportAndCleanData : Recupere les Prix
#'
#' @param urlgdoc : l'url d'un google doc provenant du site gouvernemental
#' @param urlgsheet : le titre de la feuille contenant les donnÃ©es
#'
#' @return un tibble contenant les prix du gazole, du SP98 et du E10
#' @export
#' @import googlesheets4
#' @examples
#' urlgdoctest<-"https://docs.google.com/spreadsheets/d/1aTGGqcUAjWg8Lz5sqQ5CzCEN7LbZdKGV_PdQC4YZ6Qw/edit?usp=sharing"
#' urlgsheettest<-"26-janv"
#' # you may need to relog to avoid the "Request failed [429]. Retry " error, so use
#' # gs4_auth() 
#' DonneesTest<-ImportAndCleanData(urlgdoc = urlgdoctest, urlgsheet = urlgsheettest)
#' head(DonneesTest)
ImportAndCleanData <- function(urlgdoc,urlgsheet) {
  
  Prices_daily<-googlesheets4::read_sheet(urlgdoc,urlgsheet)
  ModifPrices_daily<-Prices_daily%>%
    mutate(departement=case_when(nchar(departement)==1~as.character(paste0("0",departement)),
                                 nchar(departement)==2~as.character(departement),
                                 TRUE~as.character(departement)))
  ModifPrices_daily$trueGazole<-NA
  ModifPrices_daily$trueE10<-NA
  ModifPrices_daily$trueSP98<-NA
  
  for (i in 1:nrow(ModifPrices_daily)){
    ModifPrices_daily$trueGazole[i]<-ifelse(is.null(unlist(ModifPrices_daily$Gazole[i])[[1]]),NA,unlist(ModifPrices_daily$Gazole[i])[[1]])
    ModifPrices_daily$trueE10[i]<-ifelse(is.null(unlist(ModifPrices_daily$E10[i])[[1]]),NA,unlist(ModifPrices_daily$E10[i])[[1]])
    ModifPrices_daily$trueSP98[i]<-ifelse(is.null(unlist(ModifPrices_daily$SP98[i])[[1]]),NA,unlist(ModifPrices_daily$SP98[i])[[1]])
  }
  CleanData<-ModifPrices_daily%>%select(1:6,8,starts_with("true"))%>%
    mutate(latitude=as.numeric(latitude),
           longitude=as.numeric(latitude))%>%
    rename(Gazole=trueGazole,E10=trueE10,SP98=trueSP98)
  return(CleanData)
}
