# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' GetPrices
#'
#' @param dataset tibble un jeu de donnÃ©es propre
#' @param fonction chaine de caracteres mean ou median selon la mÃ©trique souhaite
#' @param dobydepartement logical selon qu'on veut le resultat par departement ou agrÃ©gÃ©
#'
#' @return un tibble contenant les prix moyens ou mÃ©dians du gazole, du SP98 et du E10
#' @export
#'
#' @examples
GetPrices <-
  function(dataset,
           fonction = "mean",
           dobydepartement = TRUE) {
    tmp <- dataset
    
    if (dobydepartement == TRUE & fonction == "mean") {
      sortie <- tmp %>% group_by(departement) %>%
        summarise(
          PrixGazole = mean(as.numeric(Gazole), na.rm = TRUE),
          PrixE10 = mean(as.numeric(E10), na.rm = TRUE),
          PrixSP98 = mean(as.numeric(SP98), na.rm = TRUE)
        ) %>%
        mutate(operation = fonction)
      return(sortie)
    } else if (dobydepartement == FALSE & fonction == "mean") {
      sortie <- tmp %>%mutate(departement="group")%>%group_by(departement)%>%
        summarise(
          PrixGazole = mean(as.numeric(Gazole), na.rm = TRUE),
          PrixE10 = mean(as.numeric(E10), na.rm = TRUE),
          PrixSP98 = mean(as.numeric(SP98), na.rm = TRUE)
        ) %>%
        mutate(operation = fonction)
      return(sortie)
    } else if (dobydepartement == TRUE & fonction == "median") {
      sortie <- tmp %>% group_by(departement) %>%
        summarise(
          PrixGazole = median(as.numeric(Gazole), na.rm = TRUE),
          PrixE10 = median(as.numeric(E10), na.rm = TRUE),
          PrixSP98 = median(as.numeric(SP98), na.rm = TRUE)
        ) %>%
        mutate(operation = fonction)
      return(sortie)
    } else if (dobydepartement == FALSE & fonction == "median") {
      sortie <- tmp %>%mutate(departement="group")%>%group_by(departement)%>%
        summarise(
          PrixGazole = median(as.numeric(Gazole), na.rm = TRUE),
          PrixE10 = median(as.numeric(E10), na.rm = TRUE),
          PrixSP98 = median(as.numeric(SP98), na.rm = TRUE)
        ) %>%
        mutate(operation = fonction)
      return(sortie)
    }
  }
  


